name: Testing private custom action

on:
  push:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: test
        uses: nick-invision/private-action-loader@v3
        with:
          pal-repo-token: ${{ secrets.REPO_TOKEN }}
          pal-repo-name: 3dwardCh3nG/private-gh-action@v1
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.test.outputs.random-number }}
        shell: bash
