name: Testing private custom action

on:
  push:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Get composite run steps repository
        uses: actions/checkout@v2
        with:
          repository: 3dwardCh3nG/private-gh-action
          ref: v1
          token: ${{ secrets.PAT_TOKEN }}
          path: .github/private-gh-action
      - id: foo
        name: Run action from private repo
        uses: ./.github/private-gh-action
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 60
        with:
          limit-access-to-actor: true
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
